spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_order
    username: root
    password: 2025
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8083