eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: gateway

  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_user?createDatabaseIfNotExist=true
    username: root
    password: 2025
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update


jwt:
  secret_key: c9MRwco5500VDuSMQ6ySMvKWVn+PEkdj7u3+gjKTXfY=
  refresh_expiry: 604800000
  access_expiry: 86400000
  issuer: auth-app
  audience: res-app
server:
  port: 8080