apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: restaurant-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: salah529/restaurant-microservice-auth:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/restaurant_user
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2025"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: restaurant-microservice
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
    - port: 8081
      targetPort: 8081
