apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
  namespace: restaurant-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
        - name: menu
          image: salah529/restaurant-microservice-menu:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/restaurant_menu
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2025"
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: restaurant-microservice
spec:
  type: LoadBalancer
  selector:
    app: menu
  ports:
    - port: 8082
      targetPort: 8082
