apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: restaurant-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: salah529/restaurant-microservice-order:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/restaurant_order
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2025"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: restaurant-microservice
spec:
  type: LoadBalancer
  selector:
    app: order
  ports:
    - port: 8083
      targetPort: 8083
