apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: restaurant-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: salah529/restaurant-microservice-payment:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/restaurant_payment
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2025"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: restaurant-microservice
spec:
  type: LoadBalancer
  selector:
    app: payment
  ports:
    - port: 8084
      targetPort: 8084
