apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: restaurant-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: salah529/restaurant-microservice-payment:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/payment_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: restaurant-microservice
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - port: 8083
      targetPort: 8083
