spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_user
    username: root
    password: 2025
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret_key: c9MRwco5500VDuSMQ6ySMvKWVn+PEkdj7u3+gjKTXfY=
  refresh_expiry: 604800000
  access_expiry: 86400000
  issuer: auth-app
  audience: res-app
server:
  port: 8081