server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: 2025
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
STRIPE:
  KEY:
